apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-server
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: chat-server
  template:
    metadata:
      labels:
        app: chat-server
    spec:
      containers:
      - name: chat-server
        image: chat-server
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mariadb://mariadb.default.svc.cluster.local:3306/drupal"
        - name: SPRING_DATASOURCE_USERNAME
          value: "drupal"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "drupalpass"
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: "org.hibernate.dialect.MariaDBDialect"