apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      initContainers:
      - name: init-sites-default
        image: drupal:9
        command:
          [
            "sh",
            "-c",
            "cp -n /var/www/html/sites/default/default.settings.php /mnt/sites-default/settings.php && cp -rn /var/www/html/sites/default/* /mnt/sites-default/ || true && chmod 666 /mnt/sites-default/settings.php"
          ]
        volumeMounts:
        - name: drupal-storage
          mountPath: /mnt/sites-default
      containers:
      - name: drupal
        image: drupal:9
        ports:
        - containerPort: 80
        env:
        - name: DRUPAL_DB_HOST
          value: mariadb
        - name: DRUPAL_DB_NAME
          value: drupal
        - name: DRUPAL_DB_USER
          value: drupal
        - name: DRUPAL_DB_PASSWORD
          value: drupalpass
        volumeMounts:
        - name: drupal-storage
          mountPath: /var/www/html/sites/default
      volumes:
      - name: drupal-storage
        persistentVolumeClaim:
          claimName: drupal-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: drupal-service
spec:
  type: NodePort
  selector:
    app: drupal
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
